[package]
name = "simple_ray_tracer"
version = "0.1.0"
authors = ["Inex\\Svetli"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.0"
rand = "0.7.0"
